# Server configuration
server:
  port: 8090
  contextPath:

#
jms:
  orders:
    create: orders.process.create

cxf:
  path: /ws
#  servlet:
#    init:
#      service-list-path: /ws/info
#  jaxrs:
#    component-scan: true
#    classes-scan-packages: com.william.service

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookstore
    elasticsearch:
      properties:
        path:
          logs: ./elasticsearch/log
          data: ./elasticsearch/data

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 0

  aop:
    auto: true













